name: build-test

on:
  pull_request:
  push:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: >-
            --disable-all
            --enable=vet
            --enable=ineffassign
            --enable=goconst
            --tests ./...
  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.14
        id: go-setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Test
        id: test
        run: go test -v -race ./...

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
